name: Lambda Deployment

on:
  push:
    paths:
      - 'master/**'  # Trigger the workflow when files under features_lambda/ are pushed.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Deploy Lambda Functions
        run: |
          for folder in features_lambda/*; do
            if [[ -d "$folder" ]]; then
              function_name=$(basename "$folder")
              zip -j "$function_name.zip" "$folder/lambda_code.js"
              aws lambda update-function-code --function-name "$function_name" --zip-file "fileb://$function_name.zip"
            fi
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

