name: Deploy Lambda Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine Lambda to Deploy
        id: determine-lambda
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          LAMBDA_NAME=""

          # Loop through the folder names and check if any of them are mentioned in the commit message
          # Add more folder names as needed
          for FUNCTION in lambda_1 lambda_2 lambda_3 ... lambda_50; do
            if [[ $COMMIT_MESSAGE == *"$FUNCTION"* ]]; then
              LAMBDA_NAME="$FUNCTION"
              break
            fi
          done

          if [[ -z "$LAMBDA_NAME" ]]; then
            echo "No specific Lambda to deploy."
            exit 0
          fi

          echo "::set-output name=lambda::$LAMBDA_NAME"

      - name: Deploy Lambda
        run: |
          LAMBDA_NAME="${{ steps.determine-lambda.outputs.lambda }}"
          if [[ -n "$LAMBDA_NAME" ]]; then
            cd $LAMBDA_NAME
            zip -r function.zip .
            aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb://function.zip
            cd ..
          fi

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

