name: Deploy Lambda Functions

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Identify the modified folder
      id: diff
      run: echo "MODIFIED_FOLDER=$(git diff --dirstat=1 --name-only ${{ github.event.before }} ${{ github.event.after }} | head -n 1)" >> $GITHUB_ENV

    - name: Deploy Lambda Function
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        MODIFIED_FOLDER: ${{ env.MODIFIED_FOLDER }}
      run: |
        if [ -n "$MODIFIED_FOLDER" ]; then
          echo "Modified folder: $MODIFIED_FOLDER"
          # Assuming your Lambda function is named after the folder
          function_name=$(basename $MODIFIED_FOLDER)
          zip -j function.zip "$MODIFIED_FOLDER/lambda_code.js"
          aws lambda update-function-code --function-name "$function_name" --zip-file fileb://function.zip
        else
          echo "No Lambda function folder modified."
        fi

