name: Update Lambda Functions

on:
  push:
    branches:
      - master

jobs:
  update-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: List Modified Files
        id: list-changes
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
        
      - name: Update Lambda Functions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          # Loop through the modified files
          for file in ${{ steps.list-changes.outputs.files }}; do
            if [[ $file == "lambda_"*"/index.js" ]]; then
              # Extract the function name from the path
              function_name=$(echo $file | cut -d '/' -f 1)
              echo "Updating Lambda function: $function_name"
              
              # Zip the updated Lambda function code
              cd $function_name
              zip -r function.zip .
              
              # Update the Lambda function code
              aws lambda update-function-code --function-name $function_name --zip-file fileb://function.zip
              
              # Clean up the zip file
              rm function.zip
              
              cd ..
            fi
          done

